services:
  - type: web
    name: yt-dlp
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirement.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
